name: citmatel_strawberry_trivia
description: Trivia module for CITMATEL's 'strawberry' project

publish_to: "none"

version: 1.1.0-RELEASE.20220301

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.5.1
  clean_core: ^1.2.3-RELEASE.20220206
  tuple: ^2.0.0

  # Visual & Animations
  animations: ^2.0.2
  cupertino_icons: ^1.0.2
  page_view_indicators: ^2.0.0
  liquid_progress_indicator: ^0.4.0
  flutter_svg: ^1.0.0
  im_stepper: ^0.1.3
  flutter_animator: ^3.2.0
  tutorial_coach_mark: ^1.2.1
  confetti: ^0.6.0
  auto_size_text: ^3.0.0

  #Tools
  citmatel_strawberry_tools:
    path: ../citmatel_strawberry_tools

  #DB
  objectbox: ^1.4.0
  objectbox_flutter_libs: ^1.4.0
  flat_buffers: ^2.0.5
  path_provider: ^2.0.3
  clean_repo_objectbox: ^0.2.1-SNAPSHOT.20220223

dev_dependencies:
  flutter_test:
    sdk: flutter

  #DB code generation
  build_runner: ^2.1.7
  objectbox_generator: ^1.4.0

flutter:
  assets:
    - packages/citmatel_strawberry_trivia/assets/icons/clock.svg
    - packages/citmatel_strawberry_trivia/assets/images/background.png

  uses-material-design: true
