name: citmatel_strawberry_trivia
description: Trivia module for CITMATEL's 'strawberry' project

publish_to: 'none'

version: 0.0.1-SNAPSHOT.20211202

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.5.1

  clean_core: ^1.1.2-SNAPSHOT.20211206

  cupertino_icons: ^1.0.2
  # to handle SVGs for Android, iOS, and Web
  flutter_svg: ^0.23.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/

  uses-material-design: true