name: citmatel_strawberry_trivia
description: Trivia module for CITMATEL's 'strawberry' project

publish_to: "none"

version: 0.2.0-SNAPSHOT.20220121

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.5.1
  clean_core: ^1.2.1-SNAPSHOT.20220116
  tuple: ^2.0.0

  # Visual & Animations
  animations: ^2.0.2
  cupertino_icons: ^1.0.2
  page_view_indicators: ^2.0.0
  liquid_progress_indicator: ^0.4.0
  flutter_svg: ^1.0.0
  im_stepper: ^0.1.3
  flutter_animator: ^3.2.0
  tutorial_coach_mark: ^1.2.1
  confetti: ^0.6.0

  #Modified Masters
  circular_countdown_timer:
    path: ../master/circular_countdown_timer

  #Tools
  citmatel_strawberry_tools:
    path: ../citmatel_strawberry_tools

  #DB
  objectbox: ^1.3.0
  objectbox_flutter_libs: any
  path_provider: ^2.0.3
  clean_repo_objectbox: 0.1.2-SNAPSHOT.20220116

dev_dependencies:
  flutter_test:
    sdk: flutter

  #DB code generation
  build_runner: ^2.1.7
  objectbox_generator: any

flutter:
  assets:
    - packages/citmatel_strawberry_trivia/assets/icons/clock.svg
    - packages/citmatel_strawberry_trivia/assets/images/background.jpg

  uses-material-design: true
