name: citmatel_strawberry_trivia
description: Trivia module for CITMATEL's 'strawberry' project

publish_to: 'none'

version: 0.0.1-SNAPSHOT.20211202

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.5.1
  clean_core: ^1.1.2-SNAPSHOT.20211206

  # Visual & Animations
  animations: ^2.0.2
  cupertino_icons: ^1.0.2
  page_view_indicators: ^2.0.0
  liquid_progress_indicator: ^0.4.0  
  flutter_countdown_timer: ^4.1.0
  flutter_svg: ^0.23.0+1
  im_stepper: ^0.1.3


  #Modified Masters
  circular_countdown_timer:
    path: ../master/circular_countdown_timer

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/

  uses-material-design: true